# Generated by Django 5.1.3 on 2025-02-11 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyTwoResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
                ('points', models.IntegerField(default=0)),
            ],
        ),
    ]
