# Generated by Django 5.1.3 on 2025-02-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_1', '0002_surveytworesponses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveytworesponses',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
