# Generated by Django 5.1.3 on 2025-02-12 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll_1', '0003_alter_surveytworesponses_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SurveyTwoResponses',
        ),
    ]
